### PR TITLE
Add ERNIE 3.0 based RocketQA Ranker models

### PR DESCRIPTION
**Pull request by w5688414**
### PR types

+  New features

### PR changes

+ Models

### Description

+ rocketqa-base-cross-encoder
+ rocketqa-medium-cross-encoder
+ rocketqa-mini-cross-encoder
+ rocketqa-micro-cross-encoder
+ rocketqa-nano-cross-encoder

### CODE REVIEW

**Review by tianxin1860 — DISMISSED** [review]
LGTM

**Review by LiuChiachi — DISMISSED** [review]
LGTM

**Comment by LiuChiachi** [comment]
突然想起，是否应该在这个文档里也介绍下这几个rocketqa的模型呢@tianxin1860，
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/transformers/ERNIE/contents.rst

**Review by tianxin1860 — APPROVED** [review]
LGTM

**Pull request merged**
