### PR TITLE
allow for loading from local custom transformer config 

### PR DESCRIPTION
**Pull request by BladeSun**
allow for loading from local custom transformer config 

### PR types

Bug fixes

### PR changes

Others

### Description

allow for loading from local custom transformer config without model params

### CODE REVIEW

**Comment by sijunhe** [comment]
Hi @BladeSun . Thanks for your contribution. Could you write a short code snippet to explain how you would use this feature?

**Comment by BladeSun** [comment]
> Hi @BladeSun . Thanks for your contribution. Could you write a short code snippet to explain how you would use this feature?

Hi @sijunhe, assuming I want to pretrain a ernie with 5 layers from scratch, taking advantages of the [from_pretained class method](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L348), i'll write a model_config.json under some dir, and just load the model as:
```
from paddlenlp.transformers import ErniePretrainedModel
my_ernie = ErniePretrainedModel.from_pretrained(path_to_dir)
```

Without the modification, current logic will always goto a [runtime error](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L461) when loading a local dir which only contains a single `model_config.json` file.

**Comment by sijunhe** [comment]
> Hi @sijunhe, assuming I want to pretrain a ernie with 5 layers from scratch, taking advantages of the [from_pretained class method](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L348), i'll write a model_config.json under some dir, and just load the model as:
> 
> ```
> from paddlenlp.transformers import ErniePretrainedModel
> my_ernie = ErniePretrainedModel.from_pretrained(path_to_dir)
> ```
> 
> Without the modification, current logic will always goto a [runtime error](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L461) when loading a local dir which only contains a single `model_config.json` file.

@BladeSun 
Gotcha. If you are creating a model **from scratch**, then by definition, you are **not** using a pretrained model. The appropriate API to use in this case is to directly call the constructor in this manner:

```
from paddlenlp.transformers import ErnieModel
model = ErnieModel(
        vocab_size=12345,
        hidden_size=768,
        num_hidden_layers=12,
        ...
)
```
If you want to create the model from a config file, you can do the following:
```
config: Dict = <use_json_to_read_the_config>
model = ErnieModel(**config)
```

In a future release soon, we will release `AutoConfig`, will allows you to do:
```
config = AutoConfig.from_pretrained(<local_path>)
model = ErnieModel(config)
```

Hope that explains it well!

**Comment by BladeSun** [comment]
@sijunhe Got it, many thanks, looking forward to the future release. 
I still have some doubts about the following question: If the from_pretrained class method is only designed for loading a pretrained model, why there exists some [logic](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L551) inside the method allowing for random initialization?

**Comment by sijunhe** [comment]
> @sijunhe Got it, many thanks, looking forward to the future release. I still have some doubts about the following question: If the from_pretrained class method is only designed for loading a pretrained model, why there exists some [logic](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L551) inside the method allowing for random initialization?

Thanks for point this out! This is legacy code that should probably get removed.

**Comment by sijunhe** [comment]
Thanks again for the contribution @BladeSun. Closing this PR for now.

**Pull request closed without merging**
