### PR TITLE
[NVIDIA][GPT] Fix some issues

### PR DESCRIPTION
**Pull request by Wong4j**
### PR types
Bug fixes

### PR changes
GPT: 
1. Add recompute=core_attn
2. Apply seed_guard_context to attention dropout
3. remove redundant core attn code

### CODE REVIEW

**Comment by ZHUI** [comment]
@DrownFish19

**Review by ZHUI — APPROVED** [review]

**Comment by jeng1220** [comment]
@ZHUI , all unit tests passed. Could you please merge this PR?

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/7141 
I have new pr fix for this issue.

**Comment by Wong4j** [comment]
@ZHUI 
[PR7141](https://github.com/PaddlePaddle/PaddleNLP/pull/7141) and [PR#7088](https://github.com/PaddlePaddle/PaddleNLP/pull/7088) have fixed these issues.
Close this PR.

**Pull request closed without merging**
