### PR TITLE
fix tokenizer isfile checking code

### PR DESCRIPTION
**Pull request by wj-Mcat**
### PR types
Bug fixes

### PR changes
Models

### Description
there is a stupid error in my [pr](https://github.com/PaddlePaddle/PaddleNLP/pull/2395), so I create an another pr to fix it.

```python
            elif not os.path.isfile(init_kwargs[args_name],
                                    '') and os.path.isfile(file_path):
```

changed to:

```python
            elif not os.path.isfile(init_kwargs[args_name] or 
                                    '') and os.path.isfile(file_path):
```

### CODE REVIEW

**Comment by guoshengCS** [comment]
注意使用 pre-commit ，看CodeStyle的CI没过

**Comment by wj-Mcat** [comment]
@guoshengCS 嗯嗯，我正在安装调整。

**Review by guoshengCS — APPROVED** [review]
LGTM

**Comment by guoshengCS** [comment]
Resolve #2413

**Pull request merged**
