### PR TITLE
Remove ernie-1.0 pretraining of neural search

### PR DESCRIPTION
**Pull request by w5688414**
### PR types

Function optimization
### PR changes

Others
### Description

+ Remove ernie-1.0 pretraining of neural search
+ Delete domain apaptive pretraining readme

### CODE REVIEW

**Comment by tianxin1860** [comment]
主 README 中`领域预训练` 部分需要动态图预训练加超链引导。

**Review by tianxin1860 — DISMISSED** [review]
LGTM

**Review by ZHUI — DISMISSED** [review]
LGTM

**Review by tianxin1860 — APPROVED** [review]
LGTM

**Pull request merged**
