### PR TITLE
[bug] taskflow.utils.box2example 缺少ori_boxes参数，运行报错

### PR DESCRIPTION
**Pull request by ChenBinfighting1**
### PR types

Bug fixes
### PR changes

APIs
### Description

无法使用自己的ocr结果调用taskflow实现文档抽取问答，增加对应文本区域ori_boxes参数输入

### CODE REVIEW

**Comment by ZeyuChen** [comment]
@ChenBinfighting1 Thanks for your contributions, please sign CLA thanks.

**Comment by ChenBinfighting1** [comment]
> 

hello, thanks for your reply, I have signed the CLA.
One question, it is showing ‘This branch is out-of-date with the base branch’. So do I need to switch branch submission pr?

**Review by linjieccc — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by linjieccc** [comment]
> > 
> 
> hello, thanks for your reply, I have signed the CLA. One question, it is showing ‘This branch is out-of-date with the base branch’. So do I need to switch branch submission pr?

Hi, you don't need to do that, it is already up-to-date

**Pull request merged**
