### PR TITLE
fix: fix issue #4801

### LINKED ISSUE #4801: [Bug]: ocr_process.py ocr结果处理异常
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 277, in <module>
    process_input(ocr_results, tokenizer, save_path)
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 240, in process_input
    ocr_reses = tokenize_ocr_res(ocr_reses)
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 203, in tokenize_ocr_res
    x_min, y_min = [int(min(idx)) for idx in zip(*text_box)]
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 203, in <listcomp>
    x_min, y_min = [int(min(idx)) for idx in zip(*text_box)]
TypeError: '<' not supported between instances of 'str' and 'list'

以下是para的打印数据：
{'text': [[288.0, 303.0], [638.0, 303.0], [638.0, 382.0], [288.0, 382.0]], 'bbox': [[[2530.0, 105.0], [2654.0, 105.0], [2654.0, 171.0], [2530.0, 171.0]], ('解锁', 0.993677020072937)]}
```

### 稳定复现步骤 & 代码

cd OCR_process/
python3 ocr_process.py
cd ..

### PR DESCRIPTION
**Pull request by AlexRainHao**
PR types
Bug fixes

PR changes
Demo

Description
fix #4801 , This commit try to fix #4801, which may break `doc_vqa` application. This issue effected by `paddleocr` with version > 2.6, it changed ocr result data structure

### CODE REVIEW

**Comment by sijunhe** [comment]
Thanks for the contribution!
@linjieccc please review

**Review by linjieccc — DISMISSED** [review]
LGTM, 麻烦 @1649759610  也帮忙看下哈

**Comment by AlexRainHao** [comment]
I fixed some `flake` lint errors existed before to pass the automatic lint workflow, please review it, thanks

**Review by sijunhe — APPROVED** [review]
Thanks again for the contribution!

**Pull request merged**
