### PR TITLE
Update metric cal for msra-ner

### PR DESCRIPTION
**Pull request by AI-Mart**

### CODE REVIEW

**Review by ZeyuChen — COMMENTED** [review]
不太理解这个PR修改的意义。

**Comment by AI-Mart** [comment]
> 不太理解这个PR修改的意义。

这里应该是想看所有测试集的累计评估效果吧，如果放在里面是不是只打印了最后一个batch,假如要利用返回指标寻找最优模型，放在外面算总的测试集的指标结果应该要合理些吧。

**Comment by ZeyuChen** [comment]
@LiuChiachi Please review this PR and verity is it nessasary, thanks.

**Comment by LiuChiachi** [comment]
> @LiuChiachi Please review this PR and verity is it nessasary, thanks.

I think his change is right, because `accumulate` calculates the final value.

**Review by LiuChiachi — APPROVED** [review]
LGTM

**Comment by LiuChiachi** [comment]
Better to make the PR title clearer

**Comment by AI-Mart** [comment]
好的

**Pull request merged**
