### PR TITLE
optimization  for read_func of `lcqmc`

### PR DESCRIPTION
**Pull request by jiaqianjing**
### PR types
Function optimization
### PR changes
APIs

### Description
使用内置 `lcqmc` 的方法读取其他类似文件时，遇到不合法行，跳过，而不是直接报错。比如千言数据集：paws-x-zh 中，有的行仅有 1 列数据

### CODE REVIEW

**Review by ZeyuChen — COMMENTED** [review]
Why need this optimization？Any issues？

**Comment by jiaqianjing** [comment]
> Why need this optimization？Any issues？

I got the error when I run `train_ds, dev_ds= load_dataset("lcqmc", data_files=["paws-x-zh/train.tsv", "paws-x-zh/dev.tsv"])`. Because some illegal lines in the dataset of paws-x-zh. And the two datasets have the same format.  It is not necessary to implement new function to read files.

**Comment by jiaqianjing** [comment]
> paws-x-zh

from https://aistudio.baidu.com/aistudio/competition/detail/45
image

**Comment by ZeyuChen** [comment]
@jiaqianjing Got it! Thanks for your contribution.
BTW, Is it possible to help us contribute PAWS-X dataset use LUGE dataset's link?
It would be great if more developers can use PAWS-X dataset API through your PR contribtion!
eg. 
```
load_dataset('paws_x', split=['train', 'test')]
```

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Comment by jiaqianjing** [comment]
> @jiaqianjing Got it! Thanks for your contribution.
> BTW, Is it possible to help us contribute PAWS-X dataset use LUGE dataset's link?
> It would be great if more developers can use PAWS-X dataset API through your PR contribtion!
> eg.
> 
> ```
> load_dataset('paws_x', split=['train', 'test')]
> ```

ok

**Pull request merged**
