### PR TITLE
To avoid recursive import temporarily

### PR DESCRIPTION
**Pull request by guoshengCS**
### PR types

Bug fixes 
### PR changes

Others
### Description

To avoid recursive import temporarily。

### CODE REVIEW

**Comment by LiuChiachi** [comment]
It seems that it doesn't work. 
b84343f5cf85db7e41a3d5707c444ab4



How about:
image


Because` model_utils.py` will be always imported.

**Comment by guoshengCS** [comment]
> It seems that it doesn't work. b84343f5cf85db7e41a3d5707c444ab4
> 
> How about: image
> 
> Because` model_utils.py` will be always imported.

Done. Thanks

**Review by LiuChiachi — APPROVED** [review]
LGTM

**Comment by jiweizhangxu** [comment]
66666

**Pull request merged**
