### PR TITLE
[Function optimization] Add test for autoconverter of Bert/GPT models

### PR DESCRIPTION
**Pull request by wj-Mcat**
### PR types

Function optimization

### PR changes

Tests

### Description

为Bert/GPT 模型批量添加更多的AutoConverter单测。

由于 t5 最核心的模型是 `T5Model` 和 `T5ForConditionalGeneration`，不适合批量添加更多下游模型，故在此不针对于 t5 系列模型做更多的调整。

### CODE REVIEW

**Comment by wj-Mcat** [comment]
there is an [ci error](https://github.com/PaddlePaddle/PaddleNLP/actions/runs/4034987331/jobs/6936847881) in `isort` package, it seems that it's kown issue: [pre-commit fails to install isort 5.11.4 with error "RuntimeError: The Poetry configuration is invalid"](https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co). 

So, I will try to upgrade the version of `isort` to `5.12.0`.


***

this problem is fixed by https://github.com/PaddlePaddle/PaddleNLP/pull/4538

**Comment by wj-Mcat** [comment]
Fixed by https://github.com/PaddlePaddle/PaddleNLP/pull/4538

**Comment by sijunhe** [comment]
lgtm. merge一下develop重新trigger一下lint 我再approve

**Review by sijunhe — APPROVED** [review]
lgtm

**Pull request merged**
