### PR TITLE
Add a pretrained model “CPM-Distill”

### PR DESCRIPTION
**Pull request by jm12138**
### PR types
* 添加预训练模型

### PR changes
* 添加 CPM-Distill 预训练模型

### Description
* 一个通过知识蒸馏得到的小型 GPT 预训练模型
* 源 Repo : [TsinghuaAI/CPM-Distill](https://github.com/TsinghuaAI/CPM-Distill)
* Paddle 格式的预训练模型下载 : [链接](https://bj.bcebos.com/v1/ai-studio-online/a1eabc40822b4550bc0b1d9e47f523d65516c7c0a9384d0aa5692b24d4e3b3ff?responseContentDisposition=attachment%3B%20filename%3Dgpt-cpm-small-cn-distill.pdparams)

### CODE REVIEW

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Comment by ZeyuChen** [comment]
@ZHUI Please upload the params to BOS according to the code,  then merge the code after testing.

**Comment by ZeyuChen** [comment]
@jm12138 Thanks for your contribution! :)

**Comment by ZHUI** [comment]
> @ZHUI Please upload the params to BOS according to the code,  then merge the code after testing.

ok，get it！

**Review by ZHUI — COMMENTED** [review]
LGTM

**Pull request merged**
