### PR TITLE
Enable CPU BF16 acceleration in ERNIE 3.0

### PR DESCRIPTION
**Pull request by piotrekobi**
### PR types

New features
### PR changes

Models
### Description

Adds the possibility to use the bfloat16 datatype in the ernie3.0 model.

### CODE REVIEW

**Comment by piotrekobi** [comment]
@jczaja Please review

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by piotrekobi** [comment]
@ZeyuChen @tianxin1860 Please review and merge

**Comment by jczaja** [comment]
@jiangjiajun , @Aganlengzi please start your review

**Review by jiangjiajun — APPROVED** [review]
LGTM

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@jiangjiajun @yeliang2258  Could you please help merge this PR. This adds Ernie-3.0 bf16 option.

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Comment by ZeyuChen** [comment]
@piotrekobi Thanks for your contributions!

**Pull request merged**
