### PR TITLE
[GPT3] Migrate gpt3 from fleetx into paddlenlp

### PR DESCRIPTION
**Pull request by haohongxiang**
### PR types

Others
### PR changes

Others
### Description

[GPT3] Migrate gpt3 from fleetx into paddlenlp

### CODE REVIEW

**Comment by sijunhe** [comment]
hello @haohongxiang . 麻烦按照lint结果，修改一下代码风格错误

**Review by ZHUI — APPROVED** [review]
LGTM

**Review by wawltor — APPROVED** [review]
LGTM

**Review by sneaxiy — APPROVED** [review]
LGTM

**Pull request merged**
