### PR TITLE
fix bug: NPTag postprocess

### PR DESCRIPTION
**Pull request by kev123456**

### CODE REVIEW

**Comment by linjieccc** [comment]
Thanks for your contributions! Please sign the CLA agreement @kev123456

**Review by ZeyuChen — APPROVED** [review]

**Comment by kev123456** [comment]
I signed the CLA ,please check it.

**Comment by ZeyuChen** [comment]
@kev123456 Really appreciate for your contributions!

**Comment by ZeyuChen** [comment]
@kev123456 Are you from YinXiang Note Team? I saw your PR including an email with yingxiang.com 
Does PaddleNLP model works in YinXiang's scenarios?

**Pull request merged**
