### PR TITLE
[Others] add Codegen JupyterLabExtension example

### PR DESCRIPTION
**Pull request by chenqianhe**
### PR types

Others
### PR changes

Others 
### Description

add Codegen JupyterLabExtension example

image

### CODE REVIEW

**Comment by gongel** [comment]
Great contribution!

**Review by sijunhe — CHANGES_REQUESTED** [review]
Hi @chenqianhe.
As a big JupyterLab user myself, I really like this idea! Unfortunately, I don't think your implementation should be part of PaddleNLP, as it contains too many code outside of the our tech stack (e.g. javascript, node, etc.). I think the better way is to create your own repo and use PaddleNLP as a dependency, instead of committing to PaddleNLP yourself. **We will happily link your jupyter lab extension repo in our README introducing the Codegen model**.

您好！作为一个JupyterLab的使用者，我非常开心能看到有开发者帮我们做了这个集成工作。可惜的是，因为您的代码实现和PaddleNLP本身的技术栈不太符合(例如javascript, node等等)，所以这个PR并不适合合入PaddleNLP内。我推荐您新开一个repo，然后将PaddleNLP当做依赖。**我们非常愿意在我们介绍CodeGen的README中引用你的这个工作**

**Comment by chenqianhe** [comment]
> Hi @chenqianhe. As a big JupyterLab user myself, I really like this idea! Unfortunately, I don't think your implementation should be part of PaddleNLP, as it contains too many code outside of the our tech stack (e.g. javascript, node, etc.). I think the better way is to create your own repo and use PaddleNLP as a dependency, instead of committing to PaddleNLP yourself. **We will happily link your jupyter lab extension repo in our README introducing the Codegen model**.
> 
> 您好！作为一个JupyterLab的使用者，我非常开心能看到有开发者帮我们做了这个集成工作。可惜的是，因为您的代码实现和PaddleNLP本身的技术栈不太符合(例如javascript, node等等)，所以这个PR并不适合合入PaddleNLP内。我推荐您新开一个repo，然后将PaddleNLP当做依赖。**我们非常愿意在我们介绍CodeGen的README中引用你的这个工作**

可以的，没有问题。

https://github.com/chenqianhe/codegenJupyterLabExt

**Comment by sijunhe** [comment]
merged #4002 instead

**Pull request closed without merging**
