### PR TITLE
[Recompute] Update recompute for hybrid parallel interface.

### PR DESCRIPTION
**Pull request by wuhuachaocoding**
### PR types

Others
### PR changes

Others
### Description

due to fleet api upgrading, this PR updates some interfaces for recompute.

### CODE REVIEW

**Review by ZHUI — APPROVED** [review]
LGTM

cc @sljlp 辛苦也看一下

**Comment by sljlp** [comment]
@wuhuachaocoding 看下这个改动有问题么

**Comment by sljlp** [comment]
LGTM

**Review by sljlp — APPROVED** [review]
LGTM

**Pull request merged**
