### PR TITLE
源码安装htbuilder,避免windows安装失败

### PR DESCRIPTION
**Pull request by paopjian**
### PR types

bug fix

### PR changes

pipelines/requirements.txt

### Description

使用pip git源码安装htbuilder,避免windows安装失败

### CODE REVIEW

**Comment by paopjian** [comment]
#3216

**Comment by w5688414** [comment]
> #3216

Thank you for your contribution.

**Review by w5688414 — APPROVED** [review]
LGTM

**Review by wawltor — APPROVED** [review]
LGTM

**Pull request merged**
