### PR TITLE
Add MRR metric

### PR DESCRIPTION
**Pull request by wuxin-555**
### PR types

New features
### PR changes

Others
### Description

Add MRR to paddlenlp.metrics, which can calculate the mrr metric of given label and embedding matrix.

### CODE REVIEW

**Comment by wuxin-555** [comment]
@westfish @zjjlivein @LemonNoel Could you help review my PR, please?

**Comment by w5688414** [comment]
请仿照：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/tests/metrics/test_perplexity.py

添加一下单测，本地用pytest通过后，再提交。

```
pytest -v your_tests_files
```

**Comment by wuxin-555** [comment]
> 请仿照：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/tests/metrics/test_perplexity.py
> 
> 添加一下单测，本地用pytest通过后，再提交。
> 
> ```
> pytest -v your_tests_files
> ```

I add test/metrics/test_mrr.py and finish using pytest to test my code,  and it passed. Please check it.

**Review by w5688414 — APPROVED** [review]
LGTM

**Pull request merged**
